server:
  port: 8082

spring:
  application:
    name: smartmonitor
  datasource:
    # Si will search for environment variables from the system or your docker file, and if it doesn't find them, it will use the default values after the colons
    url: jdbc:postgresql://${POSTGRES_HOST:192.168.37.128}:${POSTGRES_PORT:5433}/${POSTGRES_DB:monitor_db}
    username: ${POSTGRES_USER:postgres_admin}
    password: ${POSTGRES_PASSWORD:secure_devops_pass}
    driver-class-name: org.postgresql.Driver
    
    # Cloning SimpleConnectionPool settings from Python, but using the popular HikariCP.
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
  # Automatically convert snake_case JSON from Python into Java camelCase properties
  jackson:
    property-naming-strategy: SNAKE_CASE

  # JPA settings for Hibernate ORM
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # We're setting it to "none" for now because we haven't created the Entities yet, and to prevent Spring from checking the tables until we link them.
      ddl-auto: update # Options: none, validate, update, create, create-drop
    show-sql: true

