server:
  port: 8082

spring:
  application:
    name: smartmonitor

  # Database Configuration for PostgreSQL
  sql:
    init:
      mode: always
      schema-locations: classpath:scripts/init.sql

  datasource:
    # Si will search for environment variables from the system or your docker file, and if it doesn't find them, it will use the default values after the colons
    url: jdbc:postgresql://db:5432/monitor_db
    username: postgres_admin
    password: secure_devops_pass
    driver-class-name: org.postgresql.Driver
    
    # Cloning SimpleConnectionPool settings from Python, but using the popular HikariCP.
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 300000
      connection-timeout: 20000
  # Automatically convert snake_case JSON from Python into Java camelCase properties
  jackson:
    property-naming-strategy: SNAKE_CASE # this setting ensures that JSON properties from Python (which are typically in snake_case) are automatically converted to camelCase when deserialized into Java objects, maintaining consistency with Java naming conventions.

  # JPA settings for Hibernate ORM
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # We're setting it to "none" for now because we haven't created the Entities yet, and to prevent Spring from checking the tables until we link them.
      ddl-auto: update # Change to "update" to automatically create/update tables based on Entities, or "validate" to only validate schema without making changes.
    show-sql: true

# --- SMTP Mail Configuration for AlertService ---
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:your-email@gmail.com}
    password: secure_devops_pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# --- Custom Application Core Security & Alert Settings ---
jwt:
  # Secret key used to sign JWTs (Must be at least 256-bit / 32 characters long for HS256)
  secret: ${JWT_SECRET:9a4f2c8d3e1b7a5f9c3d2e1a4b6c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c}
  # Expiration timeframe in milliseconds (e.g., 86400000 ms = 24 Hours)
  expiration: ${JWT_EXPIRATION:86400000}

app:
  alerts:
    cpu-threshold: ${ALERT_CPU_THRESHOLD:85.0}
    ram-threshold: ${ALERT_RAM_THRESHOLD:85.0}
    disk-threshold: ${ALERT_DISK_THRESHOLD:90.0}
    # Target email address where administrator notifications will be sent
    email-to: ${ALERT_EMAIL_TO:admin@sewarl.com}
    telegram:
      # Telegram Bot Credentials configured in AlertService
      bot-token: ${TELEGRAM_BOT_TOKEN:YOUR_BOT_TOKEN}
      chat-id: ${TELEGRAM_CHAT_ID:YOUR_CHAT_ID}